version: "3.8"

services:
  spark-master:
    build:
      context: .
      dockerfile: master/Dockerfile
    container_name: spark-master
    hostname: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
      # Master doesn't need much RAM, it just orchestrates
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - big-data-network
    volumes:
      - /home/kubog/big-data-analytics/stream_preprocess:/spark/jobs
      - ./spark_checkpoints:/spark/checkpoints
      - ../hdfs/conf/core-site.xml:/spark/conf/core-site.xml
      - ../hdfs/conf/hdfs-site.xml:/spark/conf/hdfs-site.xml

  spark-worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER=spark://spark-master:7077
      # --- HEAVY DUTY CONFIG ---
      - SPARK_WORKER_MEMORY=16g
      - SPARK_WORKER_CORES=8
    ports:
      - "8081:8081"
    networks:
      - big-data-network
    # IMPORTANT: Increase shm_size to prevent crashes during heavy shuffles
    shm_size: 2gb
    volumes:
      - /home/kubog/big-data-analytics/stream_preprocess:/spark/jobs
      - ./spark_checkpoints:/spark/checkpoints
      - ../hdfs/conf/hive-site.xml:/spark/conf/hive-site.xml:ro
      - ../hdfs/conf/core-site.xml:/spark/conf/core-site.xml
      - ../hdfs/conf/hdfs-site.xml:/spark/conf/hdfs-site.xml

networks:
  big-data-network:
    external: true